version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "04:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 10
    labels: ["dependencies", "ci"]
    assignees: ["techouse"]
  - package-ecosystem: "swift"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "04:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 10
    labels: ["dependencies", "ci"]
    assignees: ["techouse"]
