name: Github release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
      - '[0-9]+.[0-9]+.[0-9]+*'

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit
  release:
    needs: test
    name: Github Release
    runs-on: ubuntu-latest
    environment: github-release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Derive VERSION from tag
        id: version
        shell: bash
        run: |
          set -euo pipefail
          TAG="${GITHUB_REF_NAME:-${GITHUB_REF#refs/tags/}}"
          VERSION="${TAG#v}"
          [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+.*$ ]] || { echo "Tag '$TAG' isn't semver-ish"; exit 1; }
          echo "TAG=$TAG" >> "$GITHUB_ENV"
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
      - name: Create tag-specific CHANGELOG
        id: create_changelog
        run: |
          set -e
          CHANGELOG_PATH=$RUNNER_TEMP/CHANGELOG.md
          awk '/^##[[:space:]].*/ { if (count == 1) exit; count++; print } count == 1 && !/^##[[:space:]].*/ { print }' CHANGELOG.md | sed -e :a -e '/^\n*$/{$d;N;ba' -e '}' > $CHANGELOG_PATH
          echo "CHANGELOG_PATH=$CHANGELOG_PATH" >> $GITHUB_ENV
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          name: ${{ env.VERSION }}
          body_path: ${{ env.CHANGELOG_PATH }}
          prerelease: ${{ contains(env.VERSION, '-') }}
      - name: Clean up
        id: clean_up
        if: ${{ always() }}
        run: rm -rf $CHANGELOG_PATH
  docs:
    uses: ./.github/workflows/docs.yml
    needs:
      - test
      - release
    permissions:
      contents: write
    secrets: inherit
